teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 0.8

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 1.5

    enable_button: 7  # L2 shoulder button
    enable_turbo_button: 3  # L1 shoulder button
